import { Dimensions, StyleSheet } from "react-native";
import { AppTheme } from "../theme/colors";
const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get("window");
export const RecentActivityStyles = (theme: AppTheme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      display: "flex",
      flexDirection: "column",
      padding: 10,
      gap: 10,
      // borderWidth: 1,
      // borderColor: theme.text,
    },
    header: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      padding: 5,
      gap: 10,
    },
    sectionTitle: {
      padding: 3,
    },
    titleText: {
      color: theme.textSecondary,
      fontSize: 17,
      fontWeight: "bold",
      // borderWidth: 1,
      // borderColor: theme.text,
    },
    sectionActions: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      padding: 5,
      gap: 5,
    },
    filterAction: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: theme.surface,
      minWidth: "15%",
      padding: 7,
      borderWidth: 1,
      borderColor: theme.border,
      borderTopLeftRadius: 10,
      borderBottomLeftRadius: 10,
    },
    showAllAction: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: theme.surface,
      minWidth: "15%",
      padding: 7,
      gap: 3,
      borderWidth: 1,
      borderColor: theme.border,
      borderTopRightRadius: 10,
      borderBottomRightRadius: 10,
    },
    showAllActionText: {
      padding: 0,
      color: theme.text,
      fontSize: 12,
      fontWeight: "bold",
    },
    body: {
      alignItems: "center",
      justifyContent: "center",
      padding: 5,
      gap: 10,
    },
    activityContainer: {
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      padding: 5,
      width: "99.9%",
      justifyContent: "space-between",
      backgroundColor: theme.surface,
      overflow: "hidden",
      borderRadius: 16,
    },
    activityIcon: {
      display: "flex",
      justifyContent: "center",
      flexDirection: "column",
      alignItems: "center",
      padding: 10,
      height:40,
      width:40,
      borderRadius: 40,
      overflow: "hidden",
      backgroundColor: theme.background,
    },
    activityTextContainer: {
      display: "flex",
      flexDirection: "column",
      gap: 2,
      width: "40%",
      overflow: "hidden",
    },

    activityTitle: {
      // borderWidth: 1,
      // borderColor: theme.text,
    },
    activityTitleText: {
      color: theme.text,
      fontSize: 13,
      fontWeight: "bold",
    },
    activitySubTitle: {
      // borderWidth: 1,
      // borderColor: theme.text,
    },
    activitySubTitleText: {
      color: theme.textSecondary,
      fontWeight: "semibold",
      fontSize: 11,
    },
    activityStatusContainer: {
      width: "5%",
      padding: 2,
      // borderWidth: 1,
      // borderColor: theme.text,
    },
    activityMetaContainer: {
      display: "flex",
      flexDirection: "column",
      gap: 3,
      width: "15%",
      overflow: "hidden",
    },
    activityAmount: {
      // borderWidth: 1,
      // borderColor: theme.text,
    },
    activityAmountText: {
      fontSize: 13,
      fontWeight: "bold",
    },
    activityDateTimeText: {
      fontSize: 9,
      fontWeight: "light",
      color: theme.textSecondary,
    },

    activityDateTime: {
      // borderWidth: 1,
      // borderColor: theme.text,
    },
    footer: {
      padding: 10,
    },
    footerOptionContainer: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      padding: 14,
      backgroundColor: theme.surface,
      borderRadius: 12,
    },
    footerOptionText: {
      color: theme.text,
      fontSize: 13,
      fontWeight: "bold",
    },
  });
