import { Dimensions, StyleSheet } from "react-native";
import { AppTheme } from "../theme/colors";
const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get("window");
export const UserAccountsSectionStyles = (theme: AppTheme) =>
  StyleSheet.create({
    container: {
      //   flex: 1,
      //   display: "flex",
      //   flexDirection: "column",
      padding: 10,
      gap: 10,
    },
    header: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      padding: 5,
      gap: 10,
    },
    sectionTitle: {
      padding: 3,
    },
    titleText: {
      color: theme.textSecondary,
      fontSize: 17,
      fontWeight: "bold",
      // borderWidth: 1,
      // borderColor: theme.text,
    },
    sectionActions: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      padding: 5,
      gap: 5,
    },
    addAction: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: theme.surface,
      minWidth: "15%",
      padding: 7,
      borderWidth: 1,
      borderColor: theme.border,
      borderTopLeftRadius: 10,
      borderBottomLeftRadius: 10,
    },
    gotoAction: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: theme.surface,
      minWidth: "15%",
      padding: 7,
      gap: 3,
      borderWidth: 1,
      borderColor: theme.border,
      borderTopRightRadius: 10,
      borderBottomRightRadius: 10,
    },
    gotoActionText: {
      padding: 0,
      color: theme.text,
      fontSize: 12,
      fontWeight: "bold",
    },
    body: {
      display: "flex",
      flexDirection: "column",
      // alignItems: "center",
      justifyContent: "center",
      width: "100%",
      overflow: "hidden",
    },
    accountCardContainer: {
      //   display: "flex",
      paddingVertical: 10,
      //   minWidth: "98%",
      //   flexDirection: "row",
      // borderWidth: 1,
      // borderColor: theme.border,
      backgroundColor: theme.background,
    },
    accountCard: {
      //   display: "flex",
      gap: 9,
      width: SCREEN_WIDTH * 0.75,
      marginRight: 15,
      borderRadius: 22,
      backgroundColor: theme.surface,
      padding: 10,
      borderWidth: 1,
      borderColor: theme.border,
    },
    cardHeader: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-between",
      minWidth: "99%",
      alignItems: "center",
    },
    accountStatusContainer: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "flex-start",
      alignItems: "center",
    },
    accountStatusText: {
      color: theme.surface,
      fontSize: 10,
    },
    moreAccountOptions: {
      paddingLeft: 10,
    },
    moreAccountOptionsDots: {
      color: theme.surface,
      fontWeight: "bold",
      fontSize: 17,
    },
    cardBody: {
      display: "flex",
      flexDirection: "column",
      minWidth: "99%",
    },
    accountDetailsContainer: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "flex-start",
      alignContent: "center",
      gap: 10,
    },
    accountDetailsIcon: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 18,
      padding: 10,

      backgroundColor: theme.surface,
    },
    accountDetails: {
      display: "flex",
      overflow:"hidden",
      flexDirection: "column",
    },
    accountName: {
      color: theme.surface,
      fontSize: 15,
      fontWeight: "bold",
    },
    accountNumber: {
      color: theme.surface,
      fontSize: 12,
      fontWeight: "semibold",
    },
    accountBalanceContainer: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "flex-start",
      alignItems: "center",
      gap: 10,
    },
    accountCurrency: {
      color: theme.surface,
      fontSize: 15,
      fontWeight: "bold",
    },
    accountBalance: {
      color: theme.surface,
      fontSize: 17,
      fontWeight: "bold",
    },
    cardFooter: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      minWidth: "99%",
    },
    accountTypeText: {
      backgroundColor: theme.foreground,
      color: theme.surface,
      // borderWidth: 1,
      fontSize: 10,
      fontWeight: "bold",
      borderRadius: 16,
      padding: 5,
    },
  });
