import { Dimensions, StyleSheet } from "react-native";
import { AppTheme } from "../theme/colors";
const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get("window");
export const ListOfAccountsStyles = (theme: AppTheme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      padding: 10,
      // display: "flex",
      // gap: 10,
    },
    containerHeader: {
      color: theme.textSecondary,
      fontWeight: "bold",
      fontSize: 13,
      textAlign: "center",
    },
    accountCardContainter: {
      display: "flex",
      width: "99%",
      marginBottom: 12,
      justifyContent: "center",
      alignItems: "center",
      // height: SCREEN_HEIGHT * 0.46,

      //   backgroundColor: theme.background,
    },
    accountCardBody: {
      display: "flex",
      gap: 9,
      // width: "96%",
      borderRadius: 16,
      backgroundColor: theme.surface,
      padding: 10,
      borderWidth: 1,
      borderColor: theme.border,
    },
    cardHeader: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-between",
      minWidth: "99%",
      alignItems: "center",
    },
    accountTypeText: {
      backgroundColor: theme.background,
      fontSize: 10,
      fontWeight: "bold",
      borderRadius: 16,
      padding: 5,
      borderWidth: 1,
      color: theme.text,
    },
    cardHeaderText: {
      color: theme.textSecondary,
      fontWeight: "bold",
      fontSize: 13,
    },
    cardBody: {
      display: "flex",
      flexDirection: "column",
      minWidth: "99%",
    },
    accountDetailsContainer: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "flex-start",
      alignContent: "center",
      gap: 10,
    },
    accountDetailsIcon: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 16,
      padding: 10,

      backgroundColor: theme.background,
    },
    accountDetails: { display: "flex", flexDirection: "column" },
    accountName: { color: theme.text, fontSize: 15, fontWeight: "bold" },
    accountNumber: { color: theme.text, fontSize: 12, fontWeight: "semibold" },
    accountBalanceContainer: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "flex-start",
      alignItems: "center",
      gap: 10,
    },
    accountCurrency: { color: theme.text, fontSize: 15, fontWeight: "bold" },
    accountBalance: { color: theme.text, fontSize: 17, fontWeight: "bold" },
    accountCardActions: {
      borderTopWidth: 1,
      borderColor: theme.border,
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      padding: 10,
      marginBottom: 5,
      //   gap: 7,
    },
    optionsIcons: {
      backgroundColor: theme.surface,
      borderRadius: 12,
      minWidth: "25%",
      borderWidth: 1,
      borderColor: theme.border,
      padding: 10,
      gap: 3,
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
    },
    optionsIconsText: {
      fontWeight: "bold",
      fontSize: 12,
      color: theme.text,
    },
  });
