import { Dimensions, StyleSheet } from "react-native";
import { AppTheme } from "../theme/colors";
const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get("window");
export const SelectedRecipientStyles = (theme: AppTheme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      padding: 10,
    },
    accountCardContainter: {
      display: "flex",
      minWidth: "98%",
      justifyContent: "center",
      alignItems: "center",
      // backgroundColor: theme.background,
    },
    accountCardBody: {
      display: "flex",
      gap: 9,
      width: SCREEN_WIDTH * 0.75,
      marginRight: 15,
      borderRadius: 16,
      backgroundColor: theme.surface,
      padding: 10,
      borderWidth: 1,
      borderColor: theme.border,
    },
    cardHeader: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-between",
      minWidth: "99%",
      alignItems: "center",
    },
    accountStatusContainer: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "flex-start",
      alignItems: "center",
    },

    accountStatusText: {
      color: theme.textSecondary,
      fontSize: 10,
    },
    cardHeaderText: {
      color: theme.textSecondary,
      fontWeight: "bold",
      fontSize: 13,
    },
    cardBody: {
      display: "flex",
      flexDirection: "column",
      minWidth: "99%",
    },
    accountDetailsContainer: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "flex-start",
      alignContent: "center",
      gap: 10,
    },
    // accountDetailsIcon: {
    //   display: "flex",
    //   alignItems: "center",
    //   justifyContent: "center",
    //   borderRadius: 16,
    //   padding: 10,

    //   backgroundColor: theme.background,
    // },
    recipientDpContainer: {
      backgroundColor: theme.background,
      width: 50,
      height: 50,
      borderRadius: 25,
      justifyContent: "center",
      alignItems: "center",
      overflow: "hidden",
    },
    recipientDp: {
      width: "100%",
      height: "100%",
    },
    iconFallBack: {
      width: "100%",
      height: "100%",
      justifyContent: "center",
      alignItems: "center",
    },
    accountDetails: { display: "flex", flexDirection: "column" },
    accountName: { color: theme.text, fontSize: 15, fontWeight: "bold" },
    accountNumber: { color: theme.text, fontSize: 12, fontWeight: "semibold" },
    accountBalanceContainer: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "flex-start",
      alignItems: "center",
      gap: 10,
      padding: 5,
    },
    accountCurrency: {
      backgroundColor: theme.background,
      fontSize: 12,
      fontWeight: "bold",
      borderRadius: 16,
      padding: 7,
      color: theme.text,
    },
    accountBalance: { color: theme.text, fontSize: 17, fontWeight: "bold" },
    accountCardActions: {
      borderTopWidth: 1,
      borderColor: theme.border,
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-end",
      padding: 3,
      gap: 10,
    },
    optionsIcons: {
      backgroundColor: theme.surface,
      borderRadius: 12,
      minWidth: "25%",
      borderWidth: 1,
      borderColor: theme.border,
      padding: 7,
      display: "flex",
      flexDirection: "row",
      gap: 3,
      justifyContent: "center",
      alignItems: "center",
    },
  });
