import { Dimensions, StyleSheet } from "react-native";
import { AppTheme } from "../theme/colors";
const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get("window");
export const GroupFinanceSectionStyles = (theme: AppTheme) =>
  StyleSheet.create({
    groupFinanceContainer: {
      padding: 5,
      gap: 5,
      justifyContent: "space-between",
      borderRadius: 30,
      // borderTopWidth: 1,
      // borderBottomWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surface,
      // alignItems: "center",
      borderWidth: 1,
      shadowColor: theme.foreground,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.4,
      shadowRadius: 8,
      elevation: 5,
    },
    groupFinanceBodyHeader: {
      flexDirection: "row",
      gap: 10,
      padding: 2,
      alignItems: "center",
      borderBottomWidth: 1,
      borderColor: theme.border,
      // borderWidth: 1,
    },
    groupFinanceUpdatedatText: {
      fontSize: 10,
      color: theme.textSecondary,
      textAlign: "left",
    },
    groupFinanceBody: {
      gap: 10,
      padding: 10,
      // borderWidth: 1,
    },
    groupFinanceBalancesContainer: {
      gap: 10,
      padding: 5,
      justifyContent:"flex-end",
      borderBottomWidth: 1,
      borderColor: theme.border,
    },
    groupFinanceBalContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    groupFinanceBalText: {
      fontSize: 12,
      color: theme.textSecondary,
      fontWeight: "bold",
    },
    groupFinanceAvailableBalNo: {
      fontSize: 34,
      color: theme.surface,
      fontWeight: "bold",
      textAlign:"right"
    },
    footer: {
      display: "flex",
      flexDirection: "row",
      gap: 5,
      minWidth: "95%",
    },
    footerCurrencyContainer: {
      display: "flex",
      justifyContent: "center",
      alignItems: "flex-start",
      minWidth: "20%",
      borderRightWidth: 2,
      borderColor: theme.border,
    },
    footerCurrencyText: {
      color: theme.surface,
      fontWeight: "bold",
      fontSize: 14,
    },
    footerBalanceTypeContainer: {
      display: "flex",
      justifyContent: "center",
      alignItems: "flex-start",
      minWidth: "70%",
    },
    footerBalanceTypeText: {
      color: theme.surface,
      fontWeight: "semibold",
      fontSize: 10,
      textAlign: "left",
    },
    groupFinanceHoldBalNo: {
      fontSize: 19,
      color: theme.surface,
      fontWeight: "bold",
    },
    groupFianceAnalysisContainer: {
      flexDirection: "row",
      // padding: 10,
      // borderWidth: 1,
      gap: 10,
      justifyContent: "center",
      alignItems: "center",
    },
    groupFinanceIncome: {
      gap: 5,
      paddingHorizontal: 5,
      // borderWidth: 1,
      justifyContent: "space-between",
      alignItems: "center",
    },
    analysisText: {
      fontSize: 11,
      color: theme.surface,
    },
    AmountText: {
      fontSize: 12,
      color: theme.surface,
      fontWeight: "bold",
    },
    groupFinanceExpenses: {
      gap: 5,
      paddingHorizontal: 20,
      borderLeftWidth: 1,
      borderColor: theme.border,
      borderRightWidth: 1,
      justifyContent: "space-between",
      alignItems: "center",
    },
    groupFinanceNetFlow: {
      gap: 5,
      paddingHorizontal: 5,
      // borderWikdth: 1,
      justifyContent: "space-between",
      alignItems: "center",
    },
    groupFinanceBodyFooter: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
      borderTopWidth: 1,
      borderColor: theme.border,
      padding: 5,
    },
    groupFinanceSectionCurrency: {
      fontSize: 13,
      fontWeight: "bold",
      color: theme.surface,
      padding: 7,
      borderWidth: 1,
      borderRadius: 17,
      justifyContent: "center",
      alignItems: "center",
      borderColor: theme.border,
    },
    groupFinanceSectionAccCount: {
      fontSize: 10,
      fontWeight: "bold",
      color: theme.textSecondary,
    },

    groupFinanceFooter: {
      flexDirection: "row",
      justifyContent: "space-between",
      paddingHorizontal: 20,
      // borderWidth: 1,
    },
    groupFinanceActions: {
      backgroundColor: theme.surface,
      borderRadius: 17,
      minWidth: "20%",
      borderWidth: 1,
      borderColor: theme.border,
      padding: 7,
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
    },
  });
