import { Dimensions, StyleSheet } from "react-native";
import { AppTheme } from "../theme/colors";
const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get("window");
export const CustomGroupHeaderStyles = (theme: AppTheme) =>
  StyleSheet.create({
    container: {
      // flex: 1,
      backgroundColor: theme.background,
      display: "flex",
      flexDirection: "row",
      minHeight: SCREEN_HEIGHT * 0.1,
      width: SCREEN_WIDTH,
      maxWidth: SCREEN_WIDTH,
      justifyContent: "space-between",
      borderBottomWidth: 2,
      borderColor: theme.border,
      overflow: "hidden",
      padding: 10,
      gap: 10,
    },
    leftContent: {
      display: "flex",
      justifyContent: "center",
      flexDirection: "row",
      alignItems: "center",
      minWidth: "20%",
    },
    groupDpContainer: {
      backgroundColor: theme.surface,
      width: 50,
      height: 50,
      borderRadius: 50,
      justifyContent: "center",
      alignItems: "center",
      overflow: "hidden",
      borderWidth: 1,
      // borderColor:theme.bo/rder,
      borderColor: theme.border,
      shadowColor: theme.foreground,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.4,
      shadowRadius: 8,
      elevation: 5,
    },
    groupDp: {
      width: "100%",
      height: "100%",
    },
    iconFallBack: {
      width: "100%",
      height: "100%",
      justifyContent: "center",
      alignItems: "center",
    },
    iconLeft: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      borderRadius: "100%",
      // backgroundColor: theme.surface,
      padding: 10,
      // shadowColor: theme.foreground,
      // shadowOffset: { width: 0, height: 0 },
      // shadowOpacity: 0.4,
      // shadowRadius: 8,
      // elevation: 5,
    },
    iconView: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      borderRadius: "100%",
      backgroundColor: theme.surface,
      padding: 10,
      shadowColor: theme.foreground,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.4,
      shadowRadius: 8,
      elevation: 5,
    },

    midContent: {
      justifyContent: "center",
      alignItems: "center",
      alignContent: "center",
      maxWidth: "45%",
      flexWrap: "wrap",
      overflow: "scroll",
      // flexWrap: "wrap",
      // borderWidth: 1,
      // borderColor: "#fefe",
    },
    groupName: {
      color: theme.foreground,
      fontWeight: "bold",
      textAlign: "center",
      fontSize: 16,
      padding: 0,
      // borderWidth: 2,
      includeFontPadding: false,
      textAlignVertical: "center",
    },
    rightContent: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      width: "20%",
      // borderWidth: 1,
      // borderColor: "rgba(175, 38, 175, 0.93)",
    },
  });
