import { Dimensions, StyleSheet } from "react-native";
import { AppTheme } from "../theme/colors";
const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get("window");
export const GroupMyPlansSectionStyles = (theme: AppTheme) =>
  StyleSheet.create({
    groupInfoContainer: {
      justifyContent: "space-between",
      padding: 10,
      backgroundColor: theme.surface,
    },
    groupInfoUpper: {
      flexDirection: "row",
      gap: 10,
      justifyContent: "space-between",
    },
    profileUpperLeft: {
      borderRadius: "100%",
      height: 80,
      width: 80,
      overflow: "hidden",
      backgroundColor: theme.surface,
      justifyContent: "center",
      alignItems: "center",
      //   padding: 10,
      borderColor: theme.border,
      borderWidth: 2,
    },
    profileUpperRight: {
      flex: 1,
      gap: 5,
      padding: 5,
      alignItems: "flex-start",
      justifyContent: "center",
      //   borderColor: "#000000",
      //   borderWidth: 2,
    },
    groupNameText: {
      fontSize: 16,
      fontWeight: "bold",
      padding: 5,
    },
    groupInfoMid: {
      padding: 5,
      //   borderColor: "#000000",
      //   borderWidth: 2,
    },
    groupTypeContainer: {
      flexDirection: "row",
      borderWidth: 1,
      borderColor: theme.border,
      padding: 5,
      borderRadius: 12,
      gap: 10,
      maxWidth: "100%",
    },
    groupTypeText: {
      fontSize: 12,
    },
    groupDescriptionText: {
      fontSize: 13,
    },

    groupInfoLower: {
      flexDirection: "row",
      justifyContent: "space-between",
      padding: 10,
      borderTopWidth: 1,
      borderColor: theme.border,
    },
    groupCountContainer: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: 10,
    },
    groupCountText: {
      fontSize: 10,
    },
    groupCreatedAtContainer: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: 10,
    },
    groupCreatedAtText: {
      fontSize: 10,
    },
    groupCreatedByContainer: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: 10,
    },
    groupCreatedByText: {
      fontSize: 10,
    },
    groupContentContainer: {
      minHeight: SCREEN_HEIGHT,
      padding: 10,
      //   borderTopWidth: 2,
      //   borderColor: theme.text,
      borderTopLeftRadius: 30,
      borderTopRightRadius: 30,
      backgroundColor: theme.background,
    },

    //timeline first
    userTimeLineContainer: {
      borderLeftWidth: 2,
      borderColor: theme.textSecondary,
      padding: 10,
    },
    userTimeLine: {
      borderBottomWidth: 1,
      borderColor: theme.border,
      padding: 5,
      justifyContent: "space-between",
    },
    timeLineHeader: {
      flexDirection: "row",
      gap: 10,
      // borderWidth: 1,
      justifyContent: "space-between",
      alignItems: "center",
    },
    timeLineHeadingContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 10,
    },
    timeLineHeadingText: {
      fontSize: 15,
      fontWeight: "bold",
    },
    timeLineQueueOptionContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 5,
    },
    timeLineQueuePrioritize: {
      flexDirection: "row",
      gap: 5,
      padding: 5,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 10,
    },
    timeLinePrioritizeText: {
      fontSize: 10,
      color: theme.textSecondary,
    },
    timeLineQueueSnooze: {
      flexDirection: "row",
      gap: 5,
      padding: 5,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 10,
    },
    timeLineSnoozeText: {
      fontSize: 10,
      color: theme.textSecondary,
    },
    timelinePlanName: {
      fontSize: 11,
      fontWeight: "bold",
      // textAlign:"center"
      color: theme.textSecondary,
      marginLeft: 10,
    },
    timelinePlanDescriptionContainer: {
      flexDirection: "row",
      padding: 10,
      gap: 5,
      alignItems: "center",
    },
    timelinePlanDescription: {
      fontSize: 12,
      fontWeight: "semibold",
      // textAlign:"center"
      marginLeft: 10,
    },
    timelineFooter: {
      flexDirection: "row",
      gap: 10,
      // padding: 10,
      justifyContent: "space-between",
      alignItems: "center",
    },
    timelineFooterDateContents: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 5,
      padding: 5,
    },
    timelineFooterActionContents: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 5,
      padding: 5,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.border,
    },
    timelineFooterDueDateText: {
      fontSize: 11,
      color: theme.textSecondary,
    },
    timelineFooterActionText: {
      fontSize: 11,
      fontWeight: "bold",
      textAlign: "center",
      color: theme.text,
    },
    groupContentHeaderContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      paddingVertical: 20,
      paddingHorizontal: 10,
    },
    groupContentHeaderText: {
      fontSize: 16,
      fontWeight: "bold",
      textAlign: "center",
      color: theme.textSecondary,
    },

    groupContentActionContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 10,
      padding: 10,
      borderColor: theme.border,
      backgroundColor: theme.surface,
      borderWidth: 2,
      borderRadius: 16,
    },
    groupContentActionText: {
      fontSize: 14,
      fontWeight: "semibold",
      color: theme.textSecondary,
    },
    myPlansContainer: {
      padding: 10,
      // borderWidth: 1,
      backgroundColor: theme.surface,
      borderRadius: 21,
      width: SCREEN_WIDTH * 0.9,
    },
    containerHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      // padding: 10,
      // gap: 10,
    },
    planTypeContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      // padding: 10,
      gap: 10,
      // borderWidth: 1,
    },
    planTypeText: {
      fontSize: 12,
    },
    planStatusContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      // padding: 10,
      gap: 10,
      // borderWidth: 1,
    },
    planStatusText: {
      fontSize: 12,
    },
    containerBody: {
      gap: 10,
      // padding: 10,
      // borderWidth: 1,
    },
    planName: {
      fontSize: 16,
      fontWeight: "bold",
    },
    planDetailsContainer: {
      flexDirection: "row",
      padding: 5,
    },
    planProgressContainerLeft: {
      justifyContent: "center",
      alignItems: "center",
      padding: 10,
      height: 90,
      width: 90,
      // backgroundColor: theme.success,
      borderRadius: 90,
      // padding: 10,
      // justifyContent: "center",
      // alignItems: "center",
      // borderRadius: 90,
      // height: 110,
      // width: 110,
      // overflow: "hidden",
      // // backgroundColor: theme.surface,
      // borderWidth: 1,
      // borderColor: theme.success,
    },
    planProgress: {
      borderWidth: 1,
      backgroundColor: theme.surface,
      borderRadius: 100,
      justifyContent: "center",
      alignItems: "center",
      height: 100,
      width: 100,
      borderColor: theme.surface,
    },
    planProgressPercentageText: {
      fontSize: 20,
      fontWeight: "bold",
      textAlign: "center",
    },
    planProgressText: {
      fontSize: 12,
      textAlign: "center",
    },
    planProgressContainerRight: {
      padding: 10,
      justifyContent: "center",
      alignItems: "flex-start",
      maxWidth: "60%",
      // borderWidth: 1,
      gap: 10,
    },
    planDescriptionText: {
      fontSize: 10,
    },
    planDateContainer: {
      flexDirection: "row",
      gap: 10,
    },
    planStartDate: {
      fontSize: 12,
      fontWeight: "bold",
    },
    planMembersContainer: {
      flexDirection: "row",
      gap: 10,
    },
    planMemberCount: {
      fontSize: 12,
      fontWeight: "bold",
    },
    containerFooter: {},
    nextEventText: {
      fontSize: 12,
      fontWeight: "bold",
    },
    groupFinanceContainer: {
      padding: 10,
      gap: 10,
      justifyContent: "space-between",
      borderRadius: 17,
      borderTopWidth: 1,
      borderBottomWidth: 1,
      borderColor: theme.border,
      // alignItems: "center",
      // borderWidth: 1,
    },
    groupFinanceBodyHeader: {
      flexDirection: "row",
      gap: 10,
      alignItems: "center",
      borderBottomWidth: 1,
      borderColor: theme.text,
      // borderWidth: 1,
    },
    groupFinanceUpdatedatText: {
      fontSize: 10,
      color: theme.textSecondary,
      textAlign: "left",
    },
    groupFinanceBody: {
      gap: 10,
      padding: 10,
      // borderWidth: 1,
    },
    groupFinanceBalancesContainer: {
      gap: 10,
      padding: 10,
      borderBottomWidth: 2,
      borderColor: theme.text,
    },
    groupFinanceBalContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    groupFinanceBalText: {
      fontSize: 12,
      color: theme.textSecondary,
      fontWeight: "bold",
    },
    groupFinanceAvailableBalNo: {
      fontSize: 23,
      color: theme.text,
      fontWeight: "bold",
    },
    groupFinanceHoldBalNo: {
      fontSize: 19,
      color: theme.text,
      fontWeight: "bold",
    },
    groupFianceAnalysisContainer: {
      flexDirection: "row",
      // padding: 10,
      // borderWidth: 1,
      gap: 10,
      justifyContent: "center",
      alignItems: "center",
    },
    groupFinanceIncome: {
      gap: 5,
      paddingHorizontal: 5,
      // borderWidth: 1,
      justifyContent: "space-between",
      alignItems: "center",
    },
    analysisText: {
      fontSize: 11,
      color: theme.text,
    },
    AmountText: {
      fontSize: 12,
      color: theme.text,
      fontWeight: "bold",
    },
    groupFinanceExpenses: {
      gap: 5,
      paddingHorizontal: 10,
      borderLeftWidth: 2,
      borderColor: theme.text,
      borderRightWidth: 2,
      justifyContent: "space-between",
      alignItems: "center",
    },
    groupFinanceNetFlow: {
      gap: 5,
      paddingHorizontal: 5,
      // borderWikdth: 1,
      justifyContent: "space-between",
      alignItems: "center",
    },
    groupFinanceBodyFooter: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      borderTopWidth: 2,
      borderColor: theme.text,
      padding: 10,
    },
    groupFinanceSectionCurrency: {
      fontSize: 13,
      fontWeight: "bold",
      color: theme.text,
      padding: 5,
      borderRightWidth: 2,
      borderColor: theme.border,
    },
    groupFinanceSectionAccCount: {
      fontSize: 12,
      fontWeight: "bold",
      color: theme.text,
    },

    groupFinanceFooter: {
      flexDirection: "row",
      justifyContent: "space-between",
      paddingHorizontal: 20,
      // borderWidth: 1,
    },
    groupFinanceActions: {
      backgroundColor: theme.surface,
      borderRadius: 12,
      minWidth: "20%",
      borderWidth: 1,
      borderColor: theme.border,
      padding: 7,
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
    },
    groupMembersContainer: {
      padding: 10,
      // borderWidth: 1,
      gap: 10,
    },
    groupMember: {
      borderRadius: 16,
      padding: 10,
      gap: 10,
      flexDirection: "row",
      alignItems: "center",
      // justifyContent: "space-between",
      backgroundColor: theme.surface,
    },
    groupMemberAvatar: {
      justifyContent: "center",
      alignItems: "center",
      borderRadius: 50,
      width: 50,
      height: 50,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.background,
    },
    groupMemberDetails: {
      gap: 3,
      alignContent: "flex-start",
      // justifyContent: "space-between",
    },
    groupMemberName: {
      fontSize: 15,
      fontWeight: "bold",
      color: theme.text,
    },
    memberDateJoined: {
      fontSize: 11,
      color: theme.textSecondary,
    },
    memberType: {
      fontSize: 10,
      // width: "auto",
      maxWidth: "50%",
      padding: 5,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 16,
      alignItems: "center",
    },
    memberRightItems: {
      flex: 1,
      // borderWidth: 1,
      flexDirection: "column-reverse",
      justifyContent: "space-between",
      alignItems: "flex-end",
    },
    sectionActions: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      padding: 5,
      gap: 5,
    },
    filterAction: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: theme.surface,
      minWidth: "15%",
      padding: 7,
      borderWidth: 1,
      borderColor: theme.border,
      borderTopLeftRadius: 10,
      borderBottomLeftRadius: 10,
    },
    showAllAction: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: theme.surface,
      minWidth: "15%",
      padding: 7,
      gap: 3,
      borderWidth: 1,
      borderColor: theme.border,
      borderTopRightRadius: 10,
      borderBottomRightRadius: 10,
    },
    showAllActionText: {
      padding: 0,
      color: theme.text,
      fontSize: 12,
      fontWeight: "bold",
    },
    groupTransactionHistoryContainer: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      padding: 10,
      gap: 10,
    },
    activityContainer: {
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      padding: 5,
      width: "99.9%",
      justifyContent: "space-between",
      backgroundColor: theme.surface,
      overflow: "hidden",
      borderRadius: 12,
    },
    activityIcon: {
      display: "flex",
      justifyContent: "center",
      flexDirection: "column",
      alignItems: "center",
      width: "14%",
      padding: 10,
      borderRadius: 10,
      overflow: "hidden",
      backgroundColor: theme.background,
    },
    activityTextContainer: {
      display: "flex",
      flexDirection: "column",
      gap: 2,
      width: "40%",
      overflow: "hidden",
    },

    activityTitle: {
      // borderWidth: 1,
      // borderColor: theme.text,
    },
    activityTitleText: {
      color: theme.text,
      fontSize: 13,
      fontWeight: "bold",
    },
    activitySubTitle: {
      // borderWidth: 1,
      // borderColor: theme.text,
      flexDirection: "row",
      gap: 10,
      alignItems: "center",
    },
    activitySubTitleText: {
      color: theme.textSecondary,
      fontWeight: "semibold",
      fontSize: 11,
    },
    activityStatusContainer: {
      width: "5%",
      padding: 2,
      // borderWidth: 1,
      // borderColor: theme.text,
    },
    activityMetaContainer: {
      display: "flex",
      flexDirection: "column",
      gap: 3,
      width: "15%",
      overflow: "hidden",
    },
    activityAmount: {
      // borderWidth: 1,
      // borderColor: theme.text,
    },
    activityAmountText: {
      fontSize: 13,
      fontWeight: "bold",
    },
    activityDateTimeText: {
      fontSize: 9,
      fontWeight: "light",
      color: theme.textSecondary,
    },

    activityDateTime: {
      // borderWidth: 1,
      // borderColor: theme.text,
    },
  });
