import { Dimensions, StyleSheet } from "react-native";
import { AppTheme } from "../theme/colors";
const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get("window");
export const GroupPageStyles = (theme: AppTheme) =>
  StyleSheet.create({
    searchRecipientsContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      overflow: "hidden",
      width: "70%",
      marginVertical: 5,
      borderWidth: 2,
      borderRadius: 16,
      borderColor: theme.border,
    },
    searchInputContainer: {
      flex: 1,
      borderRightWidth: 2,
      borderColor: theme.border,
    },
    searchInput: {
      fontSize: 15,
      fontWeight: "400",
      color: theme.textSecondary,
      textAlign: "left",
      padding: 8,
      backgroundColor: theme.surface,
      width: "100%",
      minHeight: 40,
    },
    searchInitiateContainer: {
      padding: 8,
      justifyContent: "center",
      alignItems: "center",
      minWidth: 44,
    },
    // searchInput: {
    //   fontSize: 15,
    //   fontWeight: "400",
    //   color: theme.textSecondary,
    //   textAlign: "left",
    //   padding: 8,
    //   backgroundColor: theme.surface,
    //   width: "100%",
    //   minHeight: 40,
    // },

    groupContentContainer: {
      // flex:1,
      minHeight: SCREEN_HEIGHT *0.5,
      padding: 10,
      //   borderTopWidth: 2,
      //   borderColor: theme.text,
      borderTopLeftRadius: 30,
      borderTopRightRadius: 30,
      backgroundColor: theme.background,
    },
    groupContentHeaderContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      // paddingVertical: 20,
      paddingHorizontal: 10,
    },
    groupContentHeaderText: {
      fontSize: 16,
      fontWeight: "bold",
      textAlign: "center",
      color: theme.textSecondary,
    },

    groupContentActionContainer: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: 5,
      width: SCREEN_WIDTH * 0.20,
      padding: 10,
      backgroundColor: "#17690c",
      // borderColor: theme.border,
      // backgroundColor: theme.surface,
      // borderWidth: 2,
      borderRadius: 30,
    },
    groupContentActionText: {
      fontSize: 11,
      fontWeight: "bold",
      color: theme.surface,
    },
    myPlansContainer: {
      padding: 10,
      // borderWidth: 1,
      backgroundColor: theme.surface,
      borderRadius: 21,
      width: SCREEN_WIDTH * 0.8,
    },
    sectionActions: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      padding: 5,
      gap: 5,
    },
    filterAction: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: theme.surface,
      minWidth: "15%",
      padding: 7,
      borderWidth: 1,
      borderColor: theme.border,
      borderTopLeftRadius: 10,
      borderBottomLeftRadius: 10,
    },
    showAllAction: {
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: theme.surface,
      minWidth: "15%",
      padding: 7,
      gap: 3,
      borderWidth: 1,
      borderColor: theme.border,
      borderTopRightRadius: 10,
      borderBottomRightRadius: 10,
    },
    showAllActionText: {
      padding: 0,
      color: theme.text,
      fontSize: 12,
      fontWeight: "bold",
    },
    bodySection: {
      padding: 10,
      gap: 10,
      // borderTopWidth: 1,
      // borderColor: theme.text,
    },
    rotationIntervalGroup: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      borderBottomWidth: 1,
      borderColor: theme.border,
      gap: 10,
      // padding: 10,
    },
    rotationIntervalTitle: {
      fontSize: 13,
      fontWeight: "bold",
      color: theme.text,
    },
    rotationIntervalType: {
      fontSize: 12,
      // fontWeight: "bold",
      color: theme.textSecondary,
      padding: 5,
    },
    noOfIntervals: {
      fontSize: 13,
      fontWeight: "bold",
      color: theme.text,
      padding: 5,
    },
    rotationMonetaryGroup: {
      flexDirection: "row",
      gap: 10,
    },
    contributionAmountGroup: {
      flexDirection: "row",
      gap: 10,
    },
    contributionAmountTitle: {
      fontSize: 12,
      color: theme.text,
    },
    contributionAmount: {
      fontSize: 12,
      color: theme.text,
      fontWeight: "bold",
    },
    distributionAmountGroup: {
      flexDirection: "row",
      gap: 10,
    },
    distributionAmountTitle: {
      fontSize: 12,
      color: theme.text,
    },
    distributionAmount: {
      fontSize: 12,
      color: theme.text,
      fontWeight: "bold",
    },
    rotationDatesGroup: {
      // flexDirection: "row",
      // flexWrap: "wrap",
      gap: 5,
    },
    upcomingEventDateGroup: {
      flexDirection: "row",
      gap: 5,
    },
    upcomingEventDateTitle: {
      fontSize: 12,
      color: theme.text,
      // fontWeight: "bold",
    },
    upcomingEventDate: {
      fontSize: 12,
      color: theme.text,
      fontWeight: "bold",
    },
    expectedEndDateGroup: {
      flexDirection: "row",
      gap: 5,
    },
    expectedEndDateTitle: {
      fontSize: 12,
      color: theme.text,
      // fontWeight: "bold",
    },
    expectedEndDate: {
      fontSize: 12,
      color: theme.text,
      fontWeight: "bold",
    },
    createdAtGroup: {
      flexDirection: "row",
      gap: 5,
    },
    createdAtTitle: {
      fontSize: 12,
      color: theme.text,
      // fontWeight: "bold",
    },
    createdAt: {
      fontSize: 12,
      color: theme.text,
      fontWeight: "bold",
    },
    updatedAtGroup: {
      flexDirection: "row",
      gap: 5,
    },
    updatedAtTitle: {
      fontSize: 12,
      color: theme.text,
      // fontWeight: "bold",
    },
    updatedAt: {
      fontSize: 10,
      fontWeight: "bold",
      color: theme.text,
    },
    rotationActionsGroup: {
      flexDirection: "row",
      gap: 10,
      // borderBottomWidth: 1,
      paddingTop: 5,
      justifyContent: "space-between",
      alignItems: "center",
      // borderColor: theme.border,
    },
    rotationAction: {
      flexDirection: "row",
      paddingHorizontal: 5,
      // height: 30,
      width: SCREEN_WIDTH * 0.4,
      padding: 13,
      gap: 5,
      borderRadius: 23,
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
      justifyContent: "center",
      alignItems: "center",
    },
    buttonLabel: {
      fontSize: 11,
      fontWeight: "bold",
      color: theme.surface,
    },
    scheduleContainer: {
      gap: 10,
      borderTopWidth: 1,
      borderColor: theme.border,
    },
    progressBarContainer: {
      height: 6,
      backgroundColor: "#E5E7EB",
      borderRadius: 3,
      marginTop: 6,
      overflow: "hidden",
    },
    progressBarFill: {
      height: "100%",
      width: "40%", // dynamic based on data, but we'll handle in JSX
      backgroundColor: "#0c880c",
      borderRadius: 3,
    },
    scheduleTitle: {
      fontSize: 18,
      fontWeight: "bold",
    },
    scheduleSubTitle: {
      fontSize: 13,
      color: theme.textSecondary,
    },
    intervalContainer: {
      gap: 10,
    },

    intervalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      // padding: 10,
      // borderTopWidth: 2,
      borderBottomWidth: 1,
      borderColor: theme.border,
    },
    intervalTitle: {
      fontSize: 14,
      fontWeight: "bold",
    },
    intervalDatecontainer: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      justifyContent: "space-between",
    },
    intervalDate: {
      fontSize: 9,
      fontWeight: "bold",
    },
    intervalStatuscontainer: {
      flexDirection: "row",
      gap: 5,
      justifyContent: "space-between",
      alignItems: "center",
    },
    intervalStatus: {
      fontSize: 10,
    },
    intervalEventsList: {
      gap: 5,
      // backgroundColor: theme.surface,
      overflow: "hidden",
    },
    intervalEventContainer: {
      flexDirection: "row",
      backgroundColor: theme.surface,
      borderRadius: 17,
      padding: 5,
      justifyContent: "space-between",
      alignItems: "center",
      borderBottomWidth: 1,
      borderColor: theme.border,
    },
    eventMember: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      padding: 5,
      gap: 5,
    },
    eventMemberAvator: {
      height: 30,
      width: 30,
      borderRadius: 30,
      borderWidth: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    memberName: {
      fontSize: 12,
      fontWeight: "bold",
    },
    eventAction: {
      flexDirection: "row",
      alignSelf: "center",
      gap: 5,
      padding: 5,
    },
    actionName: {
      fontSize: 10,
    },
    actionAmount: {
      fontSize: 12,
      fontWeight: "bold",
    },
    eventActionStatus: {
      flexDirection: "row",
      alignItems: "center",
      padding: 5,
      gap: 5,
    },
    actionStatus: {
      fontSize: 10,
    },
  });
