import { Dimensions, StyleSheet } from "react-native";
import { AppTheme } from "../theme/colors";
const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get("window");
export const RotationPageStyles = (theme: AppTheme) =>
  StyleSheet.create({
    container: {
      padding: 10,
      // justifyContent: "center",
      // alignItems: "center",
      gap: 10,
    },
    heroSection: {
      flexDirection: "row",
      gap: 10,
      // padding: 10,
      maxWidth: SCREEN_WIDTH * 0.98,
      // borderWidth: 1,
    },
    heroLeft: {
      justifyContent: "space-between",
      alignItems: "center",
      gap: 10,
      // borderWidth: 1,
    },
    rotationProgressContainer: {
      justifyContent: "center",
      alignItems: "center",
      padding: 10,
      height: 140,
      width: 140,
      // backgroundColor: theme.success,
      borderRadius: 140,
    },
    rotationProgressInner: {
      justifyContent: "center",
      alignItems: "center",
      padding: 10,
      height: 130,
      borderRadius: 130,
      width: 130,
      backgroundColor: theme.background,
    },
    rotationProgressNo: {
      fontSize: 20,
      fontWeight: "bold",
      color: theme.text,
    },
    rotationProgressText: {
      fontSize: 15,
      color: theme.textSecondary,
    },
    rotationRefCode: {
      fontSize: 10,
      color: theme.textSecondary,
      padding: 5,
      borderRadius: 16,
      // borderWidth: 1,
      backgroundColor: theme.surface,
    },
    heroRight: {
      flex: 1,
      padding: 10,
      gap: 10,
      // borderWidth: 1,
    },
    dateToStartContainer: {
      flexDirection: "row",
      gap: 10,
      // justifyContent: "space-between",
    },
    roationStartDate: {
      fontSize: 10,
      fontWeight: "bold",
      color: theme.text,
    },
    noOfMembersContainer: {
      flexDirection: "row",
      gap: 10,
      // justifyContent: "space-between",
    },
    noOfMembers: {
      fontSize: 10,
      fontWeight: "bold",
      color: theme.text,
    },
    rotationBadgesContainer: {
      flexDirection: "row",
      gap: 10,
      // justifyContent: "space-between",
    },
    rotationStatus: {
      justifyContent: "center",
      alignItems: "center",
      padding: 5,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 16,
      color: theme.textSecondary,
      fontSize: 10,
    },
    disbursementType: {
      justifyContent: "center",
      alignItems: "center",
      padding: 5,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 16,
      color: theme.textSecondary,
      fontSize: 10,
    },
    rotationDescriptionContainer: {
      flexDirection: "row",
      gap: 5,
      flexWrap: "wrap",
    },
    expandDescription: {},
    rotationDescription: {
      fontSize: 10,
      color: theme.textSecondary,
    },
    bodySection: {
      padding: 10,
      gap: 10,
      // borderTopWidth: 1,
      // borderColor: theme.text,
    },
    rotationIntervalGroup: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      borderBottomWidth: 1,
      borderColor: theme.border,
      gap: 10,
      // padding: 10,
    },
    rotationIntervalTitle: {
      fontSize: 13,
      fontWeight: "bold",
      color: theme.text,
    },
    rotationIntervalType: {
      fontSize: 12,
      // fontWeight: "bold",
      color: theme.textSecondary,
      padding: 5,
    },
    noOfIntervals: {
      fontSize: 13,
      fontWeight: "bold",
      color: theme.text,
      padding: 5,
    },
    rotationMonetaryGroup: {
      flexDirection: "row",
      gap: 10,
    },
    contributionAmountGroup: {
      flexDirection: "row",
      gap: 10,
    },
    contributionAmountTitle: {
      fontSize: 12,
      color: theme.text,
    },
    contributionAmount: {
      fontSize: 12,
      color: theme.text,
      fontWeight: "bold",
    },
    distributionAmountGroup: {
      flexDirection: "row",
      gap: 10,
    },
    distributionAmountTitle: {
      fontSize: 12,
      color: theme.text,
    },
    distributionAmount: {
      fontSize: 12,
      color: theme.text,
      fontWeight: "bold",
    },
    rotationDatesGroup: {
      // flexDirection: "row",
      // flexWrap: "wrap",
      gap: 5,
    },
    upcomingEventDateGroup: {
      flexDirection: "row",
      gap: 5,
    },
    upcomingEventDateTitle: {
      fontSize: 12,
      color: theme.text,
      // fontWeight: "bold",
    },
    upcomingEventDate: {
      fontSize: 12,
      color: theme.text,
      fontWeight: "bold",
    },
    expectedEndDateGroup: {
      flexDirection: "row",
      gap: 5,
    },
    expectedEndDateTitle: {
      fontSize: 12,
      color: theme.text,
      // fontWeight: "bold",
    },
    expectedEndDate: {
      fontSize: 12,
      color: theme.text,
      fontWeight: "bold",
    },
    createdAtGroup: {
      flexDirection: "row",
      gap: 5,
    },
    createdAtTitle: {
      fontSize: 12,
      color: theme.text,
      // fontWeight: "bold",
    },
    createdAt: {
      fontSize: 12,
      color: theme.text,
      fontWeight: "bold",
    },
    updatedAtGroup: {
      flexDirection: "row",
      gap: 5,
    },
    updatedAtTitle: {
      fontSize: 12,
      color: theme.text,
      // fontWeight: "bold",
    },
    updatedAt: {
      fontSize: 10,
      fontWeight: "bold",
      color: theme.text,
    },
    rotationActionsGroup: {
      flexDirection: "row",
      gap: 10,
      // borderBottomWidth: 1,
      justifyContent: "space-between",
      alignItems: "center",
      // borderColor: theme.border,
    },
    rotationAction: {
      flexDirection: "row",
      paddingHorizontal: 5,
      // height: 30,
      width: SCREEN_WIDTH * 0.4,
      padding: 13,
      gap: 5,
      borderRadius: 23,
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
      justifyContent: "center",
      alignItems: "center",
    },
    buttonLabel: {
      fontSize: 11,
      fontWeight: "bold",
      color: theme.surface,
    },
    scheduleContainer: {
      gap: 10,
      borderTopWidth: 1,
      borderColor: theme.border,
    },
    scheduleTitle: {
      fontSize: 18,
      fontWeight: "bold",
    },
    scheduleSubTitle: {
      fontSize: 13,
      color: theme.textSecondary,
    },
    intervalContainer: {
      gap: 10,
    },
    intervalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      // padding: 10,
      // borderTopWidth: 2,
      borderBottomWidth: 1,
      borderColor: theme.border,
    },
    intervalTitle: {
      fontSize: 14,
      fontWeight: "bold",
    },
    intervalDatecontainer: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      justifyContent: "space-between",
    },
    intervalDate: {
      fontSize: 9,
      fontWeight: "bold",
    },
    intervalStatuscontainer: {
      flexDirection: "row",
      gap: 5,
      justifyContent: "space-between",
      alignItems: "center",
    },
    intervalStatus: {
      fontSize: 10,
    },
    intervalEventsList: {
      gap: 5,
      // backgroundColor: theme.surface,
      overflow: "hidden",
    },
    intervalEventContainer: {
      flexDirection: "row",
      backgroundColor: theme.surface,
      borderRadius: 17,
      padding: 5,
      justifyContent: "space-between",
      alignItems: "center",
      borderBottomWidth: 1,
      borderColor: theme.border,
    },
    eventMember: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      padding: 5,
      gap: 5,
    },
    eventMemberAvator: {
      height: 30,
      width: 30,
      borderRadius: 30,
      borderWidth: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    memberName: {
      fontSize: 12,
      fontWeight: "bold",
    },
    eventAction: {
      flexDirection: "row",
      alignSelf: "center",
      gap: 5,
      padding: 5,
    },
    actionName: {
      fontSize: 10,
    },
    actionAmount: {
      fontSize: 12,
      fontWeight: "bold",
    },
    eventActionStatus: {
      flexDirection: "row",
      alignItems: "center",
      padding: 5,
      gap: 5,
    },
    actionStatus: {
      fontSize: 10,
    },
    footerSection: {},
  });
